//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentGame.UtilitiesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtilitiesService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalcAsymptoticAverage", ReplyAction="http://tempuri.org/IService1/CalcAsymptoticAverageResponse")]
        double CalcAsymptoticAverage(double[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddValueToAsymptoticAverage", ReplyAction="http://tempuri.org/IService1/AddValueToAsymptoticAverageResponse")]
        double AddValueToAsymptoticAverage(double value, double average);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : InvestmentGame.UtilitiesService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<InvestmentGame.UtilitiesService.IService1>, InvestmentGame.UtilitiesService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcAsymptoticAverage(double[] values) {
            return base.Channel.CalcAsymptoticAverage(values);
        }
        
        public double AddValueToAsymptoticAverage(double value, double average) {
            return base.Channel.AddValueToAsymptoticAverage(value, average);
        }
    }
}
